version: "3.7"


volumes:
  db-data:

services:
  logsimulator:
    image: akrawat/logsimulator:latest
    ports:
      - 8082:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.11
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cisco123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'cisco123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - db-data:/var/lib/mysql

  syslogui:
    image: akrawat/syslogui:latest
    ports:
     - 8081:8081
