version: "3.7"


volumes:
  db-data:

services:
#  mysql:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_DATABASE: glarimy
#      # So you don't have to use root, but you can if you like
#      MYSQL_USER: user
#      # You can use whatever password you like
#      MYSQL_PASSWORD: cisco123
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: cisco123
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - 3307:3306
#      # Where our data will be persisted
#    volumes:
#      - db-data:/var/lib/mysql

  logsimulator:
    image: akrawat/logsimulator:latest
    ports:
      - 8082:8080
#    depends_on:
#      - mysql
#    environment:
#      WAIT_HOSTS: mysql:3306

  syslogui:
    image: akrawat/syslogui:latest
    ports:
     - 0.0.0.0:8081:8081/tcp
     - 0.0.0.0:8081:8081/udp
