pipeline {

   agent none

   stages {
      stage('build') {
         agent {
          docker{
                 image 'maven:3.6.1-jdk-8-slim'
                 args '-v $HOME/.m2:/root/.m2'
               }
         }
         when {
            changeset "cmad-logsimulator/**"
         }
         steps {
            echo 'compiling logsimulator service'
            dir('cmad-logsimulator') {
              sh 'mvn compile'
            }
         }
      }
      stage('test') {
         agent {
          docker{
                 image 'maven:3.6.1-jdk-8-slim'
                 args '-v $HOME/.m2:/root/.m2'
               }
         }
         when {
            changeset "cmad-logsimulator/**"
         }
         steps {
            echo 'running unit tests on logsimulator service'
            dir('cmad-logsimulator') {
              sh 'mvn clean test'
            }
         }
      }
      stage('package') {
         agent {
          docker{
                 image 'maven:3.6.1-jdk-8-slim'
                 args '-v $HOME/.m2:/root/.m2'
               }
         }
         when {
            changeset "cmad-logsimulator/**"
            branch "master"
         }
         steps {
            echo 'packaging logsimulator app'
            dir('cmad-logsimulator') {
              sh 'mvn package -DskipTests'
              archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
         }
      }


      stage('docker-package'){
         agent any
         when {
            changeset "cmad-logsimulator/**"
            branch "master"
         }
         steps{
           echo 'Packaging logsimulator app with docker'
           script{
             docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {
                 def logsimulatorImage = docker.build("akrawat/logsimulator:v${env.BUILD_ID}", "cmad-logsimulator/")
                 logsimulatorImage.push()
                 logsimulatorImage.push("latest")

             }
            }
         }
      }
   }


   post{
         always{
             echo 'the job is complete'
         }
   }
}
